name: Upload scripts

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.S3_ACCESS }}
        aws-secret-access-key: ${{ secrets.S3_SECRET }}
        aws-region: ${{ vars.AWS_REGION }}
        # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        # role-duration-seconds: 1200
        # role-session-name: MySessionName
    # add --delete below to ensure orphan files removed
    - name: Sync package file.
      run: |
        aws s3 sync jq.zip s3://feher-lambda --delete